from keyboards.client_keyboard import get_client_keyboard, get_inline_keyboard, get_reg_keyboard
from keyboards.moderator_keyboard import moderator_keyboard, get_waiting_keyboard
from keyboards.admin_keyboard import keyboard_admin_default, keyboard_admin_admin, get_buttons, get_all_button_info_inline, get_buttons_pallet, malling_keyboard